import localFont from "next/font/local";
import "./globals.css";

import HeaderSection from "@/container/header/page";
import FooterSection from "@/container/footer/page";

const gilroy = localFont({
  src: [
    {
      path: "./fonts/gilroy/Gilroy-Regular.ttf", // ✅ correct (absolute path from /public)
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/gilroy/Gilroy-Regular.ttf", // ✅ correct (absolute path from /public)
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/gilroy/Gilroy-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/gilroy/Gilroy-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-gilroy",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={gilroy.variable}>
        {/* <body> */}
        <HeaderSection />

        {children}
        <FooterSection />
      </body>
    </html>
  );
}
